;;; modules.el --- Modules -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:
(add-to-list 'load-path np/module-dir)

(require 'np-basics)
(require 'np-tramp)
(require 'np-wakatime)
(require 'np-keybinds)
(require 'np-personal)
(require 'np-elisp)
(require 'np-scratch)
(require 'np-completion)
(require 'np-evil)
(require 'np-undo)
(require 'np-org)
(require 'np-yasnippet)
(require 'np-projects)
(require 'np-magit)
(require 'np-term)
(require 'np-theme)
(require 'np-flycheck)
(require 'np-treesitter)
(require 'np-python)
(require 'np-rust)
(require 'np-cpp)
(require 'np-java)
(require 'np-dashboard)
(require 'np-help)
(require 'np-which-key)
(require 'np-smartparens)
(require 'np-yaml)
(require 'np-environment)
(require 'np-lsp)
(require 'np-copilot)
(require 'np-modeline)
(require 'np-popper)
(require 'np-parrot)
;;; modules.el ends here.
