;;; modules.el --- Modules -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:
(add-to-list 'load-path np/module-dir)

(require 'np-basics)
(require 'np-general)
(require 'np-personal)
(require 'np-elisp)
(require 'np-scratch)
(require 'np-straight)
(require 'np-completion)
(require 'np-general)
(require 'np-evil)
(require 'np-undo)
(require 'np-org)
(require 'np-yasnippet)
(require 'np-projects)
(require 'np-magit)
(require 'np-term)
(require 'np-theme)
(require 'np-checker)
(require 'np-treesitter)
(require 'np-python)
(require 'np-rust)
(require 'np-dashboard)
(require 'np-helpful)
(require 'np-which-key)
(require 'np-smartparens)
(require 'np-yaml)
(require 'np-tab-bar)
(require 'np-environment)
(require 'np-lsp)
(require 'np-all-the-icons)
;;; modules.el ends here.
